# -*- coding: utf-8 -*-
"""SHAP analysis for trained PBL connector ML pipelines.

The script explains fitted sklearn pipelines saved from the group-based training
workflow. SHAP values are computed in the transformed feature space generated by
the train-only preprocessing pipeline.
"""

from __future__ import annotations

import argparse
import pickle
import re
import warnings
from pathlib import Path
from typing import Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import shap
import xgboost as xgb
from matplotlib.colors import LinearSegmentedColormap

warnings.filterwarnings("ignore")

TARGET_COL = "Pu"
ID_COL = "NO."
REF_COL = "Ref."
FEATURE_COLS = ["nh", "Sr", "Sc", "h", "d", "ds", "fsy", "fpy", "fc", "tc"]
PCA_GROUPS = [("PC1_nh_Sr", ["nh", "Sr"]), ("PC2_h_tc", ["h", "tc"])]
PCA_INPUT_COLS = ["nh", "Sr", "h", "tc"]
PASSTHROUGH_COLS = [col for col in FEATURE_COLS if col not in PCA_INPUT_COLS]
TRANSFORMED_FEATURE_NAMES = [name for name, _ in PCA_GROUPS] + PASSTHROUGH_COLS

BAR_COLOR = "#1E88E5"
SHAP_CMAP = LinearSegmentedColormap.from_list(
    "journal_blue_red",
    ["#3B8EDB", "#D81B60"],
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate SHAP plots for trained PBL ML pipelines.")
    parser.add_argument("--input", type=str, default="data/data_after_selection.xlsx", help="Input Excel file.")
    parser.add_argument("--sheet", type=str, default="0", help="Excel sheet name or index.")
    parser.add_argument("--output-dir", type=str, default="outputs/shap", help="Output directory.")
    parser.add_argument("--xgb-model", type=str, default="outputs/xgb_group_pca/xgb_group_pca_pipeline.pkl", help="Path to trained XGBoost pipeline.")
    parser.add_argument("--rf-model", type=str, default="outputs/rf_group_pca/rf_group_pca_pipeline.pkl", help="Path to trained Random Forest pipeline.")
    parser.add_argument("--models", nargs="+", default=["xgb", "rf"], choices=["xgb", "rf"], help="Models to explain.")
    parser.add_argument("--split-record", type=str, default="outputs/xgb_group_pca/main_group_split_record.csv", help="Optional split record with NO. and Set columns.")
    parser.add_argument("--explain-set", type=str, default="all", choices=["all", "train", "test"], help="Samples to explain.")
    parser.add_argument("--force-samples", nargs="+", type=int, default=[10, 100, 180], help="Human-readable sample numbers for XGBoost force plots.")
    parser.add_argument("--overlay-method", type=str, default="gaussian", choices=["none", "poly", "moving_average", "bin_mean", "gaussian"], help="Trend overlay method for dependence plots.")
    parser.add_argument("--font-family", type=str, default="Arial", help="Matplotlib font family.")
    parser.add_argument("--dpi", type=int, default=300, help="DPI for PNG outputs.")
    parser.add_argument("--tiff-dpi", type=int, default=600, help="DPI for TIFF outputs.")
    return parser.parse_args()


def parse_sheet(sheet: str) -> str | int:
    try:
        return int(sheet)
    except ValueError:
        return sheet


def safe_filename(name: str) -> str:
    name = re.sub(r"[\$\\{}]", "", str(name))
    return name.replace(" ", "_").replace("/", "_").replace("\\", "_").replace(":", "_")


def load_data(input_path: Path, sheet: str | int, split_record: Path, explain_set: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    df = pd.read_excel(input_path, sheet_name=sheet)
    required_cols = [ID_COL, REF_COL] + FEATURE_COLS + [TARGET_COL]
    missing_cols = [col for col in required_cols if col not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing columns in the input file: {missing_cols}")

    df = df.dropna(subset=FEATURE_COLS + [TARGET_COL]).copy()
    df = df[df[TARGET_COL] > 0].reset_index(drop=True)
    df["Set"] = "All"

    if split_record.exists():
        split_df = pd.read_csv(split_record)
        if ID_COL in split_df.columns and "Set" in split_df.columns:
            split_map = dict(zip(split_df[ID_COL], split_df["Set"]))
            df["Set"] = df[ID_COL].map(split_map).fillna("Unknown")

    if explain_set != "all":
        df = df[df["Set"].str.lower() == explain_set].reset_index(drop=True)
        if df.empty:
            raise ValueError(f"No samples found for explain_set='{explain_set}'.")

    X_raw = df[FEATURE_COLS].copy()
    print("=== SHAP data summary ===")
    print("Samples:", len(df))
    print("Explain set:", explain_set)
    print(df["Set"].value_counts(dropna=False))
    return df, X_raw


def load_pipeline(model_path: Path):
    if not model_path.exists():
        raise FileNotFoundError(f"Model file not found: {model_path}")
    with open(model_path, "rb") as f:
        return pickle.load(f)


def transform_features(pipeline, X_raw: pd.DataFrame) -> tuple[pd.DataFrame, object]:
    if hasattr(pipeline, "named_steps") and "preprocess" in pipeline.named_steps:
        X_arr = pipeline.named_steps["preprocess"].transform(X_raw)
        X_trans = pd.DataFrame(X_arr, columns=TRANSFORMED_FEATURE_NAMES, index=X_raw.index)
        return X_trans, pipeline.named_steps["model"]
    return X_raw.copy(), pipeline


def compute_shap_values(model_family: str, model, X_trans: pd.DataFrame):
    if model_family == "xgb":
        booster = model.get_booster()
        dmatrix = xgb.DMatrix(X_trans, feature_names=X_trans.columns.tolist())
        contribs = booster.predict(dmatrix, pred_contribs=True)
        base_value = float(contribs[0, -1])
        values = contribs[:, :-1]
        return shap.Explanation(
            values=values,
            base_values=np.full(X_trans.shape[0], base_value),
            data=X_trans.values,
            feature_names=X_trans.columns.tolist(),
        ), base_value

    explainer = shap.TreeExplainer(model)
    shap_values = explainer(X_trans)
    expected_value = explainer.expected_value
    base_value = float(np.asarray(expected_value).reshape(-1)[0])
    if np.isscalar(shap_values.base_values):
        shap_values.base_values = np.full(X_trans.shape[0], float(shap_values.base_values))
    return shap_values, base_value


def export_global_importance(shap_values, X_trans: pd.DataFrame, out_dir: Path, label: str) -> None:
    importance = pd.DataFrame(
        {
            "feature": X_trans.columns,
            "mean_abs_shap": np.abs(np.asarray(shap_values.values)).mean(axis=0),
        }
    ).sort_values("mean_abs_shap", ascending=False)
    importance.to_csv(out_dir / f"{label}_shap_global_importance.csv", index=False, encoding="utf-8-sig")


def save_shap_values(shap_values, X_trans: pd.DataFrame, df_meta: pd.DataFrame, out_dir: Path, label: str) -> None:
    shap_df = pd.DataFrame(shap_values.values, columns=[f"SHAP_{c}" for c in X_trans.columns])
    feature_df = X_trans.copy().reset_index(drop=True)
    feature_df.columns = [f"Feature_{c}" for c in feature_df.columns]
    meta_cols = [col for col in [ID_COL, REF_COL, TARGET_COL, "Set"] if col in df_meta.columns]
    out = pd.concat([df_meta[meta_cols].reset_index(drop=True), feature_df, shap_df], axis=1)
    out.to_csv(out_dir / f"{label}_all_shap_values.csv", index=False, encoding="utf-8-sig")


def plot_bar(shap_values, out_dir: Path, label: str, font_family: str, dpi: int, tiff_dpi: int) -> None:
    plt.rcParams["font.family"] = font_family
    fig = plt.figure(figsize=(8, 6), dpi=dpi)
    fig.patch.set_alpha(0.0)
    shap.plots.bar(shap_values, show=False)
    ax = plt.gca()
    ax.set_facecolor("none")
    for patch in ax.patches:
        patch.set_facecolor(BAR_COLOR)
        patch.set_edgecolor(BAR_COLOR)
    for text in list(ax.texts):
        text.remove()
    ax.grid(False)
    for line in list(ax.lines):
        line.set_visible(False)
    for collection in list(ax.collections):
        collection.set_visible(False)
    ax.xaxis.set_label_position("top")
    ax.xaxis.tick_top()
    ax.tick_params(axis="x", bottom=False, labelbottom=False, top=True, labeltop=True, labelsize=16)
    ax.tick_params(axis="y", labelsize=18)
    ax.set_xlabel("Average absolute SHAP values", fontsize=18)
    ax.spines["bottom"].set_visible(False)
    plt.tight_layout()
    plt.savefig(out_dir / f"{label}_shap_bar.png", dpi=dpi, bbox_inches="tight", transparent=True)
    plt.savefig(out_dir / f"{label}_shap_bar.tiff", dpi=tiff_dpi, bbox_inches="tight", transparent=True)
    plt.close()


def plot_beeswarm(shap_values, out_dir: Path, label: str, font_family: str, dpi: int, tiff_dpi: int) -> None:
    plt.rcParams["font.family"] = font_family
    plt.figure(figsize=(8, 6), dpi=dpi)
    shap.plots.beeswarm(shap_values, max_display=20, color=SHAP_CMAP, show=False)
    ax = plt.gca()
    ax.spines["top"].set_visible(True)
    ax.spines["right"].set_visible(True)
    ax.tick_params(axis="x", labelsize=14)
    ax.tick_params(axis="y", labelsize=18)
    ax.set_xlabel("SHAP value", fontsize=18)
    plt.tight_layout()
    plt.savefig(out_dir / f"{label}_shap_beeswarm.png", dpi=dpi, bbox_inches="tight")
    plt.savefig(out_dir / f"{label}_shap_beeswarm.tiff", dpi=tiff_dpi, bbox_inches="tight")
    plt.close()


def build_overlay_curve(x: Iterable[float], y: Iterable[float], method: str) -> tuple[np.ndarray | None, np.ndarray | None]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    x, y = x[mask], y[mask]
    if len(x) == 0 or method == "none":
        return None, None
    order = np.argsort(x)
    x, y = x[order], y[order]

    if method == "poly":
        degree = min(2, max(1, len(x) - 1))
        curve = np.poly1d(np.polyfit(x, y, degree))
        x_line = np.linspace(x.min(), x.max(), 300)
        return x_line, curve(x_line)

    if method == "moving_average":
        window = min(len(x), max(15, int(len(x) * 0.14)))
        if window < 3:
            return x, y
        x_line = np.array([np.mean(x[i:i + window]) for i in range(len(x) - window + 1)])
        y_line = np.array([np.mean(y[i:i + window]) for i in range(len(y) - window + 1)])
        return x_line, y_line

    if method == "bin_mean":
        if len(x) < 12:
            return x, y
        bins = pd.qcut(x, q=12, duplicates="drop")
        x_line, y_line = [], []
        for interval in pd.Series(bins).unique():
            idx = pd.Series(bins) == interval
            if idx.sum() >= 3:
                x_line.append(np.mean(x[idx]))
                y_line.append(np.mean(y[idx]))
        return np.asarray(x_line), np.asarray(y_line)

    if method == "gaussian":
        x_range = x.max() - x.min()
        if x_range <= 0:
            return x, y
        bandwidth = max(1e-6, x_range * 0.15)
        x_line = np.linspace(x.min(), x.max(), 300)
        y_line = []
        for x0 in x_line:
            weights = np.exp(-0.5 * ((x - x0) / bandwidth) ** 2)
            y_line.append(np.sum(weights * y) / weights.sum())
        return x_line, np.asarray(y_line)

    raise ValueError(f"Unknown overlay method: {method}")


def plot_force_plots(shap_values, base_value: float, model, X_trans: pd.DataFrame, df_meta: pd.DataFrame, out_dir: Path, sample_numbers: list[int], dpi: int, tiff_dpi: int) -> None:
    force_dir = out_dir / "xgb_force_plots"
    force_dir.mkdir(parents=True, exist_ok=True)
    records = []
    for sample_number in sample_numbers:
        idx = sample_number - 1
        if idx < 0 or idx >= len(X_trans):
            print(f"Skip force plot sample {sample_number}: index out of range.")
            continue
        shap_row = shap_values.values[idx, :]
        pred_shap = float(base_value + shap_row.sum())
        pred_model = float(model.predict(X_trans.iloc[[idx]])[0])
        plt.figure(figsize=(12, 4), dpi=dpi)
        shap.force_plot(base_value, shap_row, X_trans.iloc[idx, :], matplotlib=True, show=False)
        plt.subplots_adjust(left=0.05, right=0.95, bottom=0.30, top=0.90)
        plt.savefig(force_dir / f"xgb_shap_force_sample_{sample_number:03d}.png", dpi=dpi, bbox_inches="tight")
        plt.savefig(force_dir / f"xgb_shap_force_sample_{sample_number:03d}.tiff", dpi=tiff_dpi, bbox_inches="tight")
        plt.close()
        shap.save_html(force_dir / f"xgb_shap_force_sample_{sample_number:03d}.html", shap.force_plot(base_value, shap_row, X_trans.iloc[idx, :], matplotlib=False))

        record = {
            "human_sample_number": sample_number,
            "zero_based_index": idx,
            "base_value": base_value,
            "prediction_from_shap_sum": pred_shap,
            "prediction_from_model": pred_model,
        }
        for col in [ID_COL, REF_COL, TARGET_COL, "Set"]:
            if col in df_meta.columns:
                record[col] = df_meta.iloc[idx][col]
        records.append(record)
    if records:
        pd.DataFrame(records).to_csv(force_dir / "xgb_force_plot_sample_info.csv", index=False, encoding="utf-8-sig")


def plot_dependence(shap_values, X_trans: pd.DataFrame, df_meta: pd.DataFrame, out_dir: Path, overlay_method: str, font_family: str, dpi: int, tiff_dpi: int) -> None:
    dep_dir = out_dir / "xgb_shap_dependence"
    dep_dir.mkdir(parents=True, exist_ok=True)
    plt.rcParams["font.family"] = font_family

    for feature_name in X_trans.columns:
        values = X_trans[feature_name].to_numpy()
        shap_col = shap_values.values[:, X_trans.columns.get_loc(feature_name)]
        fname = safe_filename(feature_name)

        raw_dep = pd.DataFrame(
            {
                "sample_index": np.arange(len(X_trans)),
                "feature": feature_name,
                "feature_value": values,
                "SHAP_value": shap_col,
            }
        )
        for col in [ID_COL, REF_COL, TARGET_COL, "Set"]:
            if col in df_meta.columns:
                raw_dep[col] = df_meta[col].values
        raw_dep.to_csv(dep_dir / f"xgb_shap_dependence_{fname}_raw_data.csv", index=False, encoding="utf-8-sig")

        x_line, y_line = build_overlay_curve(values, shap_col, overlay_method)
        if x_line is not None and y_line is not None:
            pd.DataFrame(
                {
                    "feature": feature_name,
                    "feature_value": x_line,
                    "overlay_SHAP_value": y_line,
                    "overlay_method": overlay_method,
                }
            ).to_csv(dep_dir / f"xgb_shap_dependence_{fname}_overlay.csv", index=False, encoding="utf-8-sig")

        plt.figure(figsize=(8, 6), dpi=dpi)
        scatter = plt.scatter(values, shap_col, c=values, cmap=SHAP_CMAP, s=42, alpha=0.88, edgecolors="none")
        if x_line is not None and y_line is not None:
            plt.plot(x_line, y_line, color="#9467bd", linewidth=1.2, alpha=0.95, label=f"Trend ({overlay_method})")
            plt.legend(frameon=False, fontsize=12)
        plt.xlabel(feature_name, fontsize=18)
        plt.ylabel(f"SHAP value for {feature_name}", fontsize=18)
        plt.xticks(fontsize=16)
        plt.yticks(fontsize=16)
        ax = plt.gca()
        ax.spines["top"].set_visible(True)
        ax.spines["right"].set_visible(True)
        cbar = plt.colorbar(scatter)
        cbar.set_label(f"{feature_name} value", fontsize=18)
        cbar.ax.tick_params(labelsize=16)
        plt.tight_layout()
        plt.savefig(dep_dir / f"xgb_shap_dependence_{fname}.png", dpi=dpi, bbox_inches="tight")
        plt.savefig(dep_dir / f"xgb_shap_dependence_{fname}.tiff", dpi=tiff_dpi, bbox_inches="tight")
        plt.close()


def run_model(model_family: str, model_path: Path, df_meta: pd.DataFrame, X_raw: pd.DataFrame, args: argparse.Namespace) -> None:
    label = model_family
    out_dir = Path(args.output_dir) / label
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n=== Running SHAP for {model_family.upper()} ===")
    print("Model:", model_path)
    pipeline = load_pipeline(model_path)
    X_trans, model = transform_features(pipeline, X_raw)
    X_trans.to_csv(out_dir / f"{label}_transformed_features_used_for_shap.csv", index=False, encoding="utf-8-sig")

    shap_values, base_value = compute_shap_values(model_family, model, X_trans)
    save_shap_values(shap_values, X_trans, df_meta, out_dir, label)
    export_global_importance(shap_values, X_trans, out_dir, label)
    plot_bar(shap_values, out_dir, label, args.font_family, args.dpi, args.tiff_dpi)
    plot_beeswarm(shap_values, out_dir, label, args.font_family, args.dpi, args.tiff_dpi)

    if model_family == "xgb":
        plot_force_plots(shap_values, base_value, model, X_trans, df_meta, out_dir, args.force_samples, args.dpi, args.tiff_dpi)
        plot_dependence(shap_values, X_trans, df_meta, out_dir, args.overlay_method, args.font_family, args.dpi, args.tiff_dpi)

    print(f"Finished SHAP for {model_family.upper()}.")


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df_meta, X_raw = load_data(
        input_path=Path(args.input),
        sheet=parse_sheet(args.sheet),
        split_record=Path(args.split_record),
        explain_set=args.explain_set,
    )

    model_paths = {
        "xgb": Path(args.xgb_model),
        "rf": Path(args.rf_model),
    }
    for model_family in args.models:
        run_model(model_family, model_paths[model_family], df_meta, X_raw, args)

    print("\nAll SHAP outputs saved in:", output_dir)


if __name__ == "__main__":
    main()
